# Generated by Django 5.0.6 on 2024-07-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('Deptno', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100, unique=True)),
                ('Dloc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salgrade',
            fields=[
                ('Grade', models.IntegerField(primary_key=True, serialize=False)),
                ('Hsal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Lsal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Empno', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('Job', models.CharField(max_length=100)),
                ('Sal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Comm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hiredate', models.DateField(auto_now=True)),
                ('Deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
                ('mgr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp')),
            ],
        ),
    ]
